org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
minecraft_version=26.1
fabric_loader_build_version=0.18.5
fabric_loader_min_version=0.18.4
fabric_api_version=0.143.3+26.1
